### ISSUE TITLE
SCRIPT1002: Syntax error on IE 11

### ISSUE THREAD

**Issue by orckid-lab** [ibufu/vue2-scrollspy#27]
Importing vue2-scrollspy generates an error on IE11. Using laravel-mix to compile.

Error points at `eval("/* unused harmony export install */\n/* harmony import */ var`

Anyone experienced this?

**Comment by ShaneParker** [comment]
Getting the same error on IE11 using Element UI & Vue CLI 3.

Removing the following lines fixes the application, indicating that it is originating from this plugin.
```
import Scrollspy from "vue2-scrollspy";
Vue.use(Scrollspy);
```
I found the error by looking at the bundled code and seeing that IE11 doesn't understand the `=>` in the bundle. I could be wrong about the source of the issue, but it definitely is this plugin's import.

**Comment by ShaneParker** [comment]
Any update on this issue?

**Comment by ibufu** [comment]
fixed

**Comment by rdpascua** [comment]
![capture](https://user-images.githubusercontent.com/2498246/44294468-1e491680-a2ca-11e8-9bbe-3dc2930cc511.PNG)

@ibufu doesn't seem to fix on my end. I'm using IE11

**Comment by awakash** [comment]
Here's the error in IE11:
![dashboard](https://user-images.githubusercontent.com/5031120/45832705-adce5480-bcd0-11e8-9d6d-47628f693042.png)

Alludes to what @ShaneParker mentioned above:
![dashboard-2](https://user-images.githubusercontent.com/5031120/45832724-baeb4380-bcd0-11e8-838d-41077971745d.png)

Any thoughts?

**Comment by Anima-t3d** [comment]
Issue still persists

**Comment by Anima-t3d** [comment]
I think the issue is caused by having `package.json` put module as src: https://github.com/ibufu/vue2-scrollspy/blob/master/package.json#L5-L6

```
  "main": "dist/index.js",
  "module": "src/index.js",
```

If I change the following it works:
```
import Scrollspy from "vue2-scrollspy";
Vue.use(Scrollspy);
```
TO:
```
import Scrollspy from "vue2-scrollspy/dist/index";
Vue.use(Scrollspy);
```
